/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as ProjectsProjectNameRouteImport } from './routes/projects/$projectName'
import { Route as ProjectsProjectNameIndexRouteImport } from './routes/projects/$projectName.index'
import { Route as ProjectsProjectNameWorkitemsRouteImport } from './routes/projects/$projectName.workitems'
import { Route as ProjectsProjectNameSettingsRouteImport } from './routes/projects/$projectName.settings'
import { Route as ProjectsProjectNamePullrequestsRouteImport } from './routes/projects/$projectName.pullrequests'
import { Route as ProjectsProjectNameDashboardRouteImport } from './routes/projects/$projectName.dashboard'
import { Route as ProjectsProjectNameCodeRouteImport } from './routes/projects/$projectName.code'
import { Route as ProjectsProjectNameActionsRouteImport } from './routes/projects/$projectName.actions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectNameRoute = ProjectsProjectNameRouteImport.update({
  id: '/projects/$projectName',
  path: '/projects/$projectName',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectNameIndexRoute =
  ProjectsProjectNameIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameWorkitemsRoute =
  ProjectsProjectNameWorkitemsRouteImport.update({
    id: '/workitems',
    path: '/workitems',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameSettingsRoute =
  ProjectsProjectNameSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNamePullrequestsRoute =
  ProjectsProjectNamePullrequestsRouteImport.update({
    id: '/pullrequests',
    path: '/pullrequests',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameDashboardRoute =
  ProjectsProjectNameDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)
const ProjectsProjectNameCodeRoute = ProjectsProjectNameCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => ProjectsProjectNameRoute,
} as any)
const ProjectsProjectNameActionsRoute =
  ProjectsProjectNameActionsRouteImport.update({
    id: '/actions',
    path: '/actions',
    getParentRoute: () => ProjectsProjectNameRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects/$projectName': typeof ProjectsProjectNameRouteWithChildren
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectName/actions': typeof ProjectsProjectNameActionsRoute
  '/projects/$projectName/code': typeof ProjectsProjectNameCodeRoute
  '/projects/$projectName/dashboard': typeof ProjectsProjectNameDashboardRoute
  '/projects/$projectName/pullrequests': typeof ProjectsProjectNamePullrequestsRoute
  '/projects/$projectName/settings': typeof ProjectsProjectNameSettingsRoute
  '/projects/$projectName/workitems': typeof ProjectsProjectNameWorkitemsRoute
  '/projects/$projectName/': typeof ProjectsProjectNameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$projectName/actions': typeof ProjectsProjectNameActionsRoute
  '/projects/$projectName/code': typeof ProjectsProjectNameCodeRoute
  '/projects/$projectName/dashboard': typeof ProjectsProjectNameDashboardRoute
  '/projects/$projectName/pullrequests': typeof ProjectsProjectNamePullrequestsRoute
  '/projects/$projectName/settings': typeof ProjectsProjectNameSettingsRoute
  '/projects/$projectName/workitems': typeof ProjectsProjectNameWorkitemsRoute
  '/projects/$projectName': typeof ProjectsProjectNameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects/$projectName': typeof ProjectsProjectNameRouteWithChildren
  '/projects/': typeof ProjectsIndexRoute
  '/projects/$projectName/actions': typeof ProjectsProjectNameActionsRoute
  '/projects/$projectName/code': typeof ProjectsProjectNameCodeRoute
  '/projects/$projectName/dashboard': typeof ProjectsProjectNameDashboardRoute
  '/projects/$projectName/pullrequests': typeof ProjectsProjectNamePullrequestsRoute
  '/projects/$projectName/settings': typeof ProjectsProjectNameSettingsRoute
  '/projects/$projectName/workitems': typeof ProjectsProjectNameWorkitemsRoute
  '/projects/$projectName/': typeof ProjectsProjectNameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects/$projectName'
    | '/projects'
    | '/projects/$projectName/actions'
    | '/projects/$projectName/code'
    | '/projects/$projectName/dashboard'
    | '/projects/$projectName/pullrequests'
    | '/projects/$projectName/settings'
    | '/projects/$projectName/workitems'
    | '/projects/$projectName/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/projects/$projectName/actions'
    | '/projects/$projectName/code'
    | '/projects/$projectName/dashboard'
    | '/projects/$projectName/pullrequests'
    | '/projects/$projectName/settings'
    | '/projects/$projectName/workitems'
    | '/projects/$projectName'
  id:
    | '__root__'
    | '/'
    | '/projects/$projectName'
    | '/projects/'
    | '/projects/$projectName/actions'
    | '/projects/$projectName/code'
    | '/projects/$projectName/dashboard'
    | '/projects/$projectName/pullrequests'
    | '/projects/$projectName/settings'
    | '/projects/$projectName/workitems'
    | '/projects/$projectName/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsProjectNameRoute: typeof ProjectsProjectNameRouteWithChildren
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectName': {
      id: '/projects/$projectName'
      path: '/projects/$projectName'
      fullPath: '/projects/$projectName'
      preLoaderRoute: typeof ProjectsProjectNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectName/': {
      id: '/projects/$projectName/'
      path: '/'
      fullPath: '/projects/$projectName/'
      preLoaderRoute: typeof ProjectsProjectNameIndexRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/workitems': {
      id: '/projects/$projectName/workitems'
      path: '/workitems'
      fullPath: '/projects/$projectName/workitems'
      preLoaderRoute: typeof ProjectsProjectNameWorkitemsRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/settings': {
      id: '/projects/$projectName/settings'
      path: '/settings'
      fullPath: '/projects/$projectName/settings'
      preLoaderRoute: typeof ProjectsProjectNameSettingsRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/pullrequests': {
      id: '/projects/$projectName/pullrequests'
      path: '/pullrequests'
      fullPath: '/projects/$projectName/pullrequests'
      preLoaderRoute: typeof ProjectsProjectNamePullrequestsRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/dashboard': {
      id: '/projects/$projectName/dashboard'
      path: '/dashboard'
      fullPath: '/projects/$projectName/dashboard'
      preLoaderRoute: typeof ProjectsProjectNameDashboardRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/code': {
      id: '/projects/$projectName/code'
      path: '/code'
      fullPath: '/projects/$projectName/code'
      preLoaderRoute: typeof ProjectsProjectNameCodeRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
    '/projects/$projectName/actions': {
      id: '/projects/$projectName/actions'
      path: '/actions'
      fullPath: '/projects/$projectName/actions'
      preLoaderRoute: typeof ProjectsProjectNameActionsRouteImport
      parentRoute: typeof ProjectsProjectNameRoute
    }
  }
}

interface ProjectsProjectNameRouteChildren {
  ProjectsProjectNameActionsRoute: typeof ProjectsProjectNameActionsRoute
  ProjectsProjectNameCodeRoute: typeof ProjectsProjectNameCodeRoute
  ProjectsProjectNameDashboardRoute: typeof ProjectsProjectNameDashboardRoute
  ProjectsProjectNamePullrequestsRoute: typeof ProjectsProjectNamePullrequestsRoute
  ProjectsProjectNameSettingsRoute: typeof ProjectsProjectNameSettingsRoute
  ProjectsProjectNameWorkitemsRoute: typeof ProjectsProjectNameWorkitemsRoute
  ProjectsProjectNameIndexRoute: typeof ProjectsProjectNameIndexRoute
}

const ProjectsProjectNameRouteChildren: ProjectsProjectNameRouteChildren = {
  ProjectsProjectNameActionsRoute: ProjectsProjectNameActionsRoute,
  ProjectsProjectNameCodeRoute: ProjectsProjectNameCodeRoute,
  ProjectsProjectNameDashboardRoute: ProjectsProjectNameDashboardRoute,
  ProjectsProjectNamePullrequestsRoute: ProjectsProjectNamePullrequestsRoute,
  ProjectsProjectNameSettingsRoute: ProjectsProjectNameSettingsRoute,
  ProjectsProjectNameWorkitemsRoute: ProjectsProjectNameWorkitemsRoute,
  ProjectsProjectNameIndexRoute: ProjectsProjectNameIndexRoute,
}

const ProjectsProjectNameRouteWithChildren =
  ProjectsProjectNameRoute._addFileChildren(ProjectsProjectNameRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsProjectNameRoute: ProjectsProjectNameRouteWithChildren,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
